version: '3.8'

services:
  kratz-art:
    build:
      context: .
      dockerfile: /app
    ports:
      - "4000:3000"
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production